In [1]:
!pip install transformers

Requirement already satisfied: transformers in c:\users\patil\anaconda3\lib\site-packages (5.10.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\patil\anaconda3\lib\site-packages (from transformers) (1.18.0)
Requirement already satisfied: numpy>=1.17 in c:\users\patil\anaconda3\lib\site-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\patil\appdata\roaming\python\python313\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\patil\anaconda3\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\patil\anaconda3\lib\site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\patil\anaconda3\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\patil\anaconda3\lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\patil\anaconda3\lib\site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\patil\anaconda3\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: click>=8.4.0 in c:\users\patil\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\patil\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\patil\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\patil\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\patil\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\patil\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.12.2)
Requirement already satisfied: anyio in c:\users\patil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.7.0)
Requirement already satisfied: certifi in c:\users\patil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\patil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\patil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\patil\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\patil\anaconda3\lib\site-packages (from typer->transformers) (1.5.0)
Requirement already satisfied: rich>=13.8.0 in c:\users\patil\anaconda3\lib\site-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\patil\anaconda3\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: colorama in c:\users\patil\appdata\roaming\python\python313\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\patil\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\patil\appdata\roaming\python\python313\site-packages (from rich>=13.8.0->typer->transformers) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\patil\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\patil\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)

In [2]:
!pip install "transformers[torch]"

Requirement already satisfied: transformers[torch] in c:\users\patil\anaconda3\lib\site-packages (5.10.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\patil\anaconda3\lib\site-packages (from transformers[torch]) (1.18.0)
Requirement already satisfied: numpy>=1.17 in c:\users\patil\anaconda3\lib\site-packages (from transformers[torch]) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\patil\appdata\roaming\python\python313\site-packages (from transformers[torch]) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\patil\anaconda3\lib\site-packages (from transformers[torch]) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\patil\anaconda3\lib\site-packages (from transformers[torch]) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\patil\anaconda3\lib\site-packages (from transformers[torch]) (0.22.2)
Requirement already satisfied: typer in c:\users\patil\anaconda3\lib\site-packages (from transformers[torch]) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\patil\anaconda3\lib\site-packages (from transformers[torch]) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\patil\anaconda3\lib\site-packages (from transformers[torch]) (4.67.1)
Requirement already satisfied: torch>=2.4 in c:\users\patil\anaconda3\lib\site-packages (from transformers[torch]) (2.12.0+cu126)
Requirement already satisfied: accelerate>=1.1.0 in c:\users\patil\anaconda3\lib\site-packages (from transformers[torch]) (1.13.0)
Requirement already satisfied: click>=8.4.0 in c:\users\patil\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\patil\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\patil\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\patil\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\patil\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\patil\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.12.2)
Requirement already satisfied: anyio in c:\users\patil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.7.0)
Requirement already satisfied: certifi in c:\users\patil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\patil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.0.9)
Requirement already satisfied: idna in c:\users\patil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\patil\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\patil\anaconda3\lib\site-packages (from typer->transformers[torch]) (1.5.0)
Requirement already satisfied: rich>=13.8.0 in c:\users\patil\anaconda3\lib\site-packages (from typer->transformers[torch]) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\patil\anaconda3\lib\site-packages (from typer->transformers[torch]) (0.0.4)
Requirement already satisfied: psutil in c:\users\patil\appdata\roaming\python\python313\site-packages (from accelerate>=1.1.0->transformers[torch]) (6.1.1)
Requirement already satisfied: colorama in c:\users\patil\appdata\roaming\python\python313\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\patil\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers[torch]) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\patil\appdata\roaming\python\python313\site-packages (from rich>=13.8.0->typer->transformers[torch]) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\patil\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers[torch]) (0.1.0)
Requirement already satisfied: setuptools<82 in c:\users\patil\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (72.1.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\patil\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\patil\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\patil\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\patil\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=2.4->transformers[torch]) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\patil\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\patil\anaconda3\lib\site-packages (from jinja2->torch>=2.4->transformers[torch]) (3.0.2)

In [3]:
import pandas as pd
from transformers import T5Tokenizer, Trainer, TrainingArguments, T5ForConditionalGeneration

In [65]:
train_data = pd.read_csv("samsum-train.csv")
val_data = pd.read_csv("samsum-validation.csv")

In [66]:
train_data.head()

,id,dialogue,summary
0,13818513,Amanda: I baked cookies. Do you want some?\r\...,Amanda baked cookies and will bring Jerry some...
1,13728867,Olivia: Who are you voting for in this electio...,Olivia and Olivier are voting for liberals in ...
2,13681000,"Tim: Hi, what's up?\r\nKim: Bad mood tbh, I wa...",Kim may try the pomodoro technique recommended...
3,13730747,"Edward: Rachel, I think I'm in ove with Bella....",Edward thinks he is in love with Bella. Rachel...
4,13728094,Sam: hey overheard rick say something\r\nSam:...,"Sam is confused, because he overheard Rick com..."

In [67]:
train_data["dialogue"][0]

"Amanda: I baked  cookies. Do you want some?\r\nJerry: Sure!\r\nAmanda: I'll bring you tomorrow :-)"

In [68]:
print("Training Data:- ", train_data.shape)
print("Validation Data",val_data.shape)

Training Data:-  (14732, 3)
Validation Data (818, 3)

In [69]:
# Random Sampling
train_data = train_data.sample(n=8000, random_state= 42).reset_index(drop= True)
val_data = val_data.sample(n=500, random_state= 42).reset_index(drop = True)

In [70]:
train_data.head()

,id,dialogue,summary
0,13811908,Violet: hi! i came across this Austin's articl...,Violet sent Claire Austin's article.
1,13716431,Pat: So does anyone know when the stream is go...,Pat and Lou are waiting for The stream but Kev...
2,13810214,Jane: <gif_file>\r\nJane: Whaddya think? \r\nS...,Jane is updating her Tinder profile tonight an...
3,13729823,"Adam: Do u have a map of Paris?\r\nTom: Yes, W...",Tom has a map of Paris.
4,13681400,"Frank: Hi, how's the family?\r\nMike: great! S...","Mike is happy, because Sam's moved out. Mike a..."

In [71]:
print("Training Data:- ", train_data.shape)
print("Validation Data",val_data.shape)

Training Data:-  (8000, 3)
Validation Data (500, 3)

# Data Preprocessing

In [72]:
import re

def clean_data(text):
    text = re.sub(r"\r\n", " ", text) # lines
    text = re.sub(r"\s+", " ", text)  # spaces
    text = re.sub(r"<.*?>>", " ", text)  # html tags <br>
    text = text.strip().lower()
    return text

In [73]:
train_data["dialogue"] = train_data["dialogue"].apply(clean_data)
train_data["summary"] = train_data["summary"].apply(clean_data)

val_data["dialogue"] = val_data["dialogue"].apply(clean_data)
val_data["summary"] = val_data["summary"].apply(clean_data)

In [74]:
train_data["dialogue"][0]

"violet: hi! i came across this austin's article and i thought that you might find it interesting violet: <file_other> claire: hi! :) thanks, but i've already read it. :) claire: but thanks for thinking about me :)"

# Tokenize

In [75]:
tokenizer = T5Tokenizer.from_pretrained("t5-small")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

C:\Users\patil\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\patil\.cache\huggingface\hub\models--t5-small. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

In [88]:
# raw data => tokenize inputs for fine tunning
def tokenize(data):
    inputs = tokenizer(data["dialogue"], padding="max_length", max_length = 512 , truncation= True)
    targets = tokenizer(data["summary"], padding="max_length", max_length = 150 , truncation= True)

    inputs["labels"] = targets["input_ids"] # token ids => add to input as labels
    return inputs

In [89]:
train_dataset = train_data.apply(tokenize, axis = 1).tolist()   # convert into list because this huggingface model is compatible with list data
val_dataset = val_data.apply(tokenize, axis = 1).tolist()

In [90]:
train_dataset[0]

{'input_ids': [25208, 10, 7102, 55, 3, 23, 764, 640, 48, 403, 17, 77, 31, 7, 1108, 11, 3, 23, 816, 24, 25, 429, 253, 34, 1477, 25208, 10, 3, 2, 11966, 834, 9269, 3155, 3, 7997, 15, 10, 7102, 55, 3, 10, 61, 2049, 6, 68, 3, 23, 31, 162, 641, 608, 34, 5, 3, 10, 61, 3, 7997, 15, 10, 68, 2049, 21, 1631, 81, 140, 3, 10, 61, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'labels': [25208, 1622, 3, 7997, 15, 403, 17, 77, 31, 7, 1108, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

In [94]:
# input ids
# 1 => End of sequence
# attention mask   ==> it is tells us that which input value is original and which is padding using 1(original) & 0 (padding)
# labels - target => summery token

In [93]:
len(train_dataset[0]["input_ids"])

512

In [95]:
type(train_dataset)

list

# working with out model

In [96]:
# NLP => Generation Task
model = T5ForConditionalGeneration.from_pretrained("t5-small")

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [97]:
# Fine- tune

In [105]:
import torch

if torch.cuda.is_available():
    device = torch.device("cuda")
    print("device:", device)
model.to(device)

device: cuda

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=512, out_features=32128, bias=False)
)

In [108]:
# Training Arguments

training_args = TrainingArguments(
    output_dir= "./results",
    num_train_epochs= 5,
    weight_decay= 0.01,
    per_device_train_batch_size = 8,
    per_device_eval_batch_size = 8,
    eval_strategy=  "epoch",
    save_strategy= "epoch",
    warmup_steps= 500
    # 0 => learning rate
)

In [109]:
trainer = Trainer(
    model = model,
    args = training_args,
    train_dataset= train_dataset,
    eval_dataset= val_dataset
)

In [110]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=5000, training_loss=0.69954423828125, metrics={'train_runtime': 2033.1898, 'train_samples_per_second': 19.674, 'train_steps_per_second': 2.459, 'total_flos': 5413672058880000.0, 'train_loss': 0.69954423828125, 'epoch': 5.0})

 model load => fine tune (on our purticular dataset) => save the model

# save the model

In [112]:
model.save_pretrained("./saved_summary_model")
tokenizer.save_pretrained("./saved_summary_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./saved_summary_model\\tokenizer_config.json',
 './saved_summary_model\\tokenizer.json')

In [114]:
model = T5ForConditionalGeneration.from_pretrained("./saved_summary_model")
tokenizer = T5Tokenizer.from_pretrained("./saved_summary_model")

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

## Test the core logic for summerization

In [1]:
def summarize_dialogue(dialogue):
    dialogue = clean_data(dialogue)  # clean

    # tokenize
    inputs =  tokenizer(
        dialogue,
        padding= "max_length",
        max_length = 512,
        trucation = True,
        return_tensors = "pt"  # hugging face model are build on the pytorch
    )
    # generate the summary => token ids
    model.to(device)
    targets = model.generate(
        input_ids= inputs["input_ids"],
        attension_mask = inputs["attension_mask"],
        max_length = 150,
        num_beams = 4,
        early_stopping = True
    )
    # token ids converts into text  or summary  =>  it is called as decoding
    summary = tokenizer.decode(targets[0], skip_special_tokens= True) # End of Sequence, Separation
    return summary