In [46]:
import pandas as pd

In [47]:
df = pd.read_csv("IMDB_Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [48]:
df.shape

(50000, 2)

In [49]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [50]:
# No of duplicates in datast
df.duplicated().value_counts()

False    49582
True       418
Name: count, dtype: int64

In [51]:
df.drop_duplicates(inplace= True)

In [52]:
df.shape

(49582, 2)

## Pre-processing

### 1. Convert into lowecase

In [53]:
df["review"] = df["review"].str.lower()

### 2. Removing Url's

In [54]:
import re
def remove_urls(text):
    text = re.sub(r"http\S+", "", text) # (Pattern, replace, string) eg - https://www.google.com 
    return text 
df["review"] = df["review"].apply(remove_urls)

### 3. Removing Punctuations

In [55]:
def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s]", "", text) # [^A-Za-z0-9] other than this range all replace by white space
                                               # this ^ is used for negation that execept A-Za-z0-9 replce by white space
    return text
df["review"] =  df["review"].apply(remove_punctuations)

### 4. Removing Html Tag's

In [56]:
def remove_html(text):
    text = re.sub(r"<.*?>", "", text)
    return text
df["review"] = df["review"].apply(remove_html)

### 5. Remove the Stopwords

In [57]:
import nltk
nltk.download("punkt")   # Tokenizer 
nltk.download("punkt_tab") 
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

##### Punkt Sentence Tokenizer.
##### This tokenizer divides a text into a list of sentences by using an unsupervised algorithm to build a model for abbreviation words, collocations, and words that start sentences. It must be trained on a large collection of plaintext in the target language before it can be used.
##### The NLTK data package includes a pre-trained Punkt tokenizer for English.

In [59]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [67]:
# test = "I love code in python !"
# token = word_tokenize(test)
# print(token)
# OutputL:-
# ['I', 'love', 'code', 'in', 'python', '!']

In [70]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_word = stopwords.words("english")

    for word in tokens:
        if word in stop_word:
            text = text.replace(word, "")

    return text
df["review"] = df["review"].apply(remove_stopwords)

In [71]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1   wderful ltle producti br br  filming techniqu...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly res  fmly   lttle boy jke thks res  zom...  negative
4  petter mtte love   time  mey   vully stunng fi...  positive

### 6. Stemming

In [74]:
# Running -> run
# played -> play
from nltk.stem import PorterStemmer

In [75]:
def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []
    
    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)

    return " ".join(stemmed_words)
    
df["review"] = df["review"].apply(stemming)

In [76]:
df.head()

                                              review sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...  positive
1  wder ltle producti br br film techniqu unssum ...  positive
2  thought th wder wy spend tme o hot summer week...  positive
3  bsclli re fmli lttle boy jke thk re zomb close...  negative
4  petter mtte love time mey vulli stunng film wt...  positive

### 7. Encoding

In [77]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["sentiment"] = le.fit_transform(df["sentiment"])

In [79]:
y = df["sentiment"]
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

### 8. Vectorization

In [81]:
# We convert this text data into numbers
df.head()

                                              review  sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...          1
1  wder ltle producti br br film techniqu unssum ...          1
2  thought th wder wy spend tme o hot summer week...          1
3  bsclli re fmli lttle boy jke thk re zomb close...          0
4  petter mtte love time mey vulli stunng film wt...          1

In [86]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features= 10000)
X = tf.fit_transform(df["review"])

In [93]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4412616 stored elements and shape (49582, 10000)>
  Coords	Values
  (0, 7133)	0.05357721771247686
  (0, 5754)	0.09093418954101587
  (0, 9882)	0.11139303607807532
  (0, 6037)	0.4585043288085252
  (0, 2645)	0.13188637950315826
  (0, 4617)	0.048084350796945854
  (0, 3925)	0.07686273874242902
  (0, 7165)	0.09364011604160272
  (0, 2794)	0.059862197812292114
  (0, 3973)	0.05979959250094263
  (0, 435)	0.08343246635123416
  (0, 3284)	0.07170561895782888
  (0, 8785)	0.040793001284708
  (0, 8388)	0.17290549700171423
  (0, 550)	0.10395391952610282
  (0, 7476)	0.03257305541956315
  (0, 9501)	0.26032395745463277
  (0, 7691)	0.0430096405070769
  (0, 9571)	0.057092907095546507
  (0, 3531)	0.036447650247323306
  (0, 9045)	0.07396276365639927
  (0, 7799)	0.170362527346317
  (0, 3313)	0.05966749204320836
  (0, 3794)	0.0722051990956081
  (0, 6715)	0.06223560211057084
  :	:
  (49581, 9034)	0.09080226749257932
  (49581, 871)	0.10857261839819735
  (49581, 8591)	0.10523679708747197
  (49581, 3965)	0.09640548870204695
  (49581, 1121)	0.08128932318285835
  (49581, 4436)	0.13683297736576325
  (49581, 4486)	0.09201359697253396
  (49581, 8729)	0.16894515264380106
  (49581, 9312)	0.11165634949526311
  (49581, 7376)	0.0842727828010317
  (49581, 9494)	0.11921084948103688
  (49581, 3998)	0.12346955483251934
  (49581, 1059)	0.12041917357598025
  (49581, 5263)	0.1673350663338149
  (49581, 8953)	0.1544132164997764
  (49581, 4397)	0.18318375843981285
  (49581, 8132)	0.19395496225063527
  (49581, 4881)	0.19125493006712382
  (49581, 672)	0.14266720495541654
  (49581, 5407)	0.16790873926505379
  (49581, 880)	0.1285650901690732
  (49581, 9955)	0.1456668057348796
  (49581, 3576)	0.15260955491617956
  (49581, 7027)	0.14664714341908328
  (49581, 7026)	0.17971391881664436

# Dataset & DataLoaders

In [96]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size= 0.2, random_state= 42
)

In [97]:
X_train.shape

(39665, 10000)

In [98]:
X_test.shape

(9917, 10000)

In [101]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [100]:
# we can not pass the direct "Compressed Sparse Row sparse matrix" to the Tensor Dataset 
# to pass data need to convert into numpy array
X_train = X_train.toarray()
X_test = X_test.toarray()

In [102]:
train_set = TensorDataset(
    # we can directly convert x_train and y_train into the pytorch tensor
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()
)
test_set = TensorDataset(
    # we can directly convert x_train and y_train into the pytorch tensor
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
)

In [103]:
train_loader = DataLoader(train_set, batch_size= 64, shuffle= True)
test_loader = DataLoader(test_set, batch_size= 64)

# Build our RNN

In [111]:
import torch.nn as nn
import torch.optim as optim

In [122]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size= 128, num_layers = 1):
        super().__init__()
    
        self.hidden_size = hidden_size
        # self.input_size = input_size
        self.num_layers = num_layers
        # RNN Layer
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first= True)

        #fully Connected Layer
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        # optinal => shape (num of layers, batch size, hidden layer)
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)

        out, _ = self.rnn(x, h0)
        # 1st output => hidden value  of all timesteps => (batch, seq_len, hidden_size)
        # 2nd output => final hidden state of last timestep
# from 1st out put the fully connected layer expect all batch, only last seq_len, and all hidden size that why we pass only required value "out[:,-1,:]"
        out= self.fc(out[:,-1,:])
        return out

In [123]:
input_size = X_train.shape[1]

model = RNN(input_size)
criterion = nn.BCELoss() # Binary Cross Entropy Loss (used when only two output)
optimizer = optim.Adam(model.parameters())

# Training the RNN

In [124]:
epochs = 10 
for epoch in range(epochs):
    model.train()

    for Xb, yb in train_loader:
        optimizer.zero_grad()
        Xb = Xb.unsqueeze(1) # add singleton direction
        
        outputs = model(Xb)
        outputs = torch.sigmoid(outputs.squeeze()) # (batch_size, ) => probability
        
        loss= criterion(outputs, yb) # compute loss
        loss.backward() # back prop
        optimizer.step() # weights update

    print(f"epoch ={epoch+1}/{epochs} and loss = {loss.item()}  ")

epoch =1/10 and loss = 0.31899702548980713
epoch =2/10 and loss = 0.28846025466918945
epoch =3/10 and loss = 0.13879694044589996
epoch =4/10 and loss = 0.18322843313217163
epoch =5/10 and loss = 0.17691324651241302
epoch =6/10 and loss = 0.22941015660762787
epoch =7/10 and loss = 0.38204318284988403
epoch =8/10 and loss = 0.13852344453334808
epoch =9/10 and loss = 0.3442208766937256
epoch =10/10 and loss = 0.05604909732937813

# Evaluate

In [127]:
model.eval()
with torch.no_grad():
    correct_vals = 0
    tot_val = 0
    for Xb, yb in test_loader:
        Xb = Xb.unsqueeze(1)
        
        outputs = model(Xb)
        predicted = (torch.sigmoid(outputs.squeeze())>0.5).float()
        
        tot_val += yb.size(0)
        correct_vals += (predicted == yb).sum().item()

    print(f"accuracy ={correct_vals/tot_val *100}")

accuracy =84.29968740546536