In [100]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score
import seaborn as sns
import pandas as pd

In [25]:
data = pd.read_csv("heart.csv")
# data.nunique()
# data.info()
# data.columns
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [30]:
data["thal"].unique()

array([1, 2, 3, 0])

In [35]:
X = data.drop(columns=["target"])
y = data["target"]

In [39]:
X.head()
# y.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

# Train Test Split

In [44]:
X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size =0.2, random_state = 42
)

In [95]:
y_train[y_train==1] # 133
y_train[y_train==0] # 109

202    0
196    0
176    0
177    0
258    0
      ..
257    0
214    0
302    0
188    0
270    0
Name: target, Length: 109, dtype: int64

In [75]:
model = LogisticRegression(max_iter=2000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=2000)

In [77]:
y_pred =model.predict(X_test)

# Accuracy & precision score

In [97]:
print("Accuracy Score :- ",accuracy_score(y_test,y_pred))
print("Precision Score :- ",precision_score(y_test,y_pred))

Accuracy Score :-  0.8852459016393442
Precision Score :-  0.8787878787878788

In [78]:
r2_score(y_test,y_pred)

0.5398706896551724